### ISSUE TITLE
ERROR: Service 'app' failed to build: failed to register layer

### ISSUE THREAD

**Issue by johndpope** [bitrise-docker/android#114] opened 2017-09-13 10:34 UTC
docker-compose build
Building app
Step 1/2 : FROM bitriseio/docker-android-alpha:v2017_09_07-10_07-b740
v2017_09_07-10_07-b740: Pulling from bitriseio/docker-android-alpha
d5c6f90da05d: Pull complete
1300883d87d5: Pull complete
c220aa3cfc1b: Pull complete
2e9398f099dc: Pull complete
dc27a084064f: Pull complete
0ef4a414627e: Pull complete
b83c75e2a6da: Pull complete
245984c2578b: Pull complete
311e47bb25be: Pull complete
76c01ca93a54: Pull complete
0377946bac9f: Pull complete
3d29e62346e0: Pull complete
4ad4612bb28e: Pull complete
85d419a9432c: Pull complete
682d3d164e30: Pull complete
f9576fc24db7: Pull complete
ff0c79ceadc2: Pull complete
641351f736ec: Pull complete
f2b93c57cc80: Pull complete
9052905b61e3: Pull complete
08d839440305: Pull complete
58ee3f2f0936: Pull complete
5debbf426d77: Pull complete
0ec94d1ff7a0: Pull complete
0e9f1844f4f8: Pull complete
0756ee63a2c5: Pull complete
966e2e6ef565: Pull complete
ff58c7ec545e: Pull complete
335ab6bd65e4: Pull complete
b49924d94054: Pull complete
3f38b007dfdf: Pull complete
472f6fc23b1d: Pull complete
535c328da709: Pull complete
47b394ff27f0: Pull complete
8d0305cad43b: Extracting [==================================================>]  3.299GB/3.299GB
adb9df30c1ca: Download complete
da00211b70a0: Download complete
9fe11c547123: Download complete
8e280529f2c0: Download complete
474cc66f18df: Download complete
fdfb176291be: Download complete
825e38f7ada2: Download complete
91c8eb75222c: Download complete
938b8a57d688: Download complete
ERROR: Service 'app' failed to build: failed to register layer: Error processing tar file(exit status 1): write /opt/android-sdk-linux/platforms/android-22/data/res/values-ml-rIN/strings.xml: no space left on device

will try with the --squash option.

**Comment by viktorbenei** [comment] 2017-09-13 10:36
the issue is:

> no space left on device

do you run this on Mac?

**Comment by viktorbenei** [comment] 2017-09-13 10:37
Just to be sure, "no space left on device" means that there's not enough disk space *on your device*. If you're on Mac then Docker runs in a virtual machine and this error comes from the virtual machine, that the VM doesn't have enough disk space

**Comment by viktorbenei** [comment] 2017-09-13 16:15
I'll close this issue as it doesn't seem to be related to this repo (as mentioned above), but feel free to comment and we'll answer or reopen!

**Closed by viktorbenei** 2017-09-13 16:15 UTC
Labels: question
